#!/bin/bash
## This script is under GPL v3 License (http://www.gnu.org/licenses/gpl-3.0.html).

zenity --warning --text "This script is under GPL v3 License >> coded by awan_venom"
again='y'
while  [ $again == 'y' ] || [ $again == 'Y' ];
do
clear
#Dont add anything under this code
cyan='\e[0;36m'
green='\e[0;34m'
nyala='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
item='\e[1;30m'
bah='\e[1;33m'

#dont delete/edit/change my intro!! except you are lamer/plagiarism
echo -e $bah'   _______         .__     __   ____   ________ 
   \      \__  _  _|  |___/  |_ \   \ /   /_   |   
   /   |   \ \/ \/ /  |  \   __\ \   Y   / |   |	
  /    |    \     /|   Y  \  |    \     /  |   | 
  \____|__  /\/\_/ |___|  /__| /\  \___/   |___|	
          \/            \/     \/'$red'codename : NKRI'
echo -e $red '[x]'$nyala' WELCOME on > Wireless Hacking TOols'
echo -e $red '[x]'$white 'c0ded by awan_venom'$red'    <-Author-> '$white'AJ4l_13'
echo -e $red '[x]'$white 'kecoakteam3[at]gmail.com'$red' <-report bugs'
echo -e $red '[x]'$nyala 'Tested On Backtrack 5R3 ,Kalilinux'
echo ""
echo -e $red'Select From Menu :'
echo -e $white"       0) Download User Guide "
echo          "       1) Cracking Wifi WPA" 
echo          "       2) Cracking Wifi WPA2" 
echo          "       3) Wireless Hacking GUI" 
echo          "       4) WPS Hacking Tool" 
echo          "       5) Wifi-Honey" #done
echo          "       6) Network Traffic Monitor" 
echo          "       7) Network Stress Testing" 
echo          "       8) Network Forensics" 
echo          "       9) Another Tools For Wireless Hacking" 
echo          "       X) Credits & About"
echo          "       Q) Exit"
echo ""
echo -n -e $red'\033[4mNWHT\033[0m'$red '> '; tput sgr0 #insert your choice
read choose
if test $choose == '1'
 then
	sh njepat/autoWPA-ng

elif test $choose == '2'
 then
	sh njepat/autoWPA2-ng

elif test $choose == '3'
 then
	sh njepat/WGUI
	
elif test $choose == '4'
 then
	sh njepat/autoreaverX
	
elif test $choose == '5'
 then
 echo -n -e $red "Insert Your ESSID (nameFakeWifi)! : > "; tput sgr0
	read essid
 echo -n -e $red "Insert Your Channel do you want! : > "; tput sgr0
	read channelcuy
	iwconfig
 echo -n -e $red "Insert Your Interface (default wlan0)! : > "; tput sgr0
	read apaan
sh wifi_honey.sh $essid $channelcuy $apaan
	
elif test $choose == '6'
 then
	sh njepat/NTM

elif test $choose == '7'
 then
	sh njepat/xDOS
 
elif test $choose == '8'
 then
 sh njepat/autoNetworkForensics

elif test $choose == '9'
 then
 sh njepat/ATFWH

elif test $choose == 'X'
	then
	clear
zenity --info --text "DISCLAIMER: modifications, changes, or alterations to this sourcecode is acceptable, however, any public releases utilizing this code must be approved by writen this tool 
Thanks to all my friend on facebook and suport special thanks to > My God Allah | My parents | My sister | and My Girlfriend
Special Thanks for your nice ideas and help to make this tool more useful:

zenity --warning --text "Dont forget to report Bug >> kecoakteam3[at]gmail.com"

elif test $choose == '0'
 then
	gnome-terminal --command="wget https://www.dropbox.com/s/zry7gvuqpa75v/README.pdf"

elif test $choose == 'Q'
 then
 clear
echo -e $red '                               /T /I
                              / |/ | .-~/
                          T\ Y  I  |/  /  _
         /T               | \I  |  I  Y.-~/
        I l   /I       T\ |  |  l  |  T  /
     T\ |  \ Y l  /T   | \I  l   \    l Y
 __  | \l   \l  \I l __l  l   \      _. |
 \ ~-l   \    \  \  \\ ~\  \    . .-~   |
  \   ~-. \-.  \  \  ^._ ^. --.  /  \   |
.--~-._  ~-  \  _  ~-_.---.- ._ /._ ./ ./
 >--.  ~-.   ._  ~>--    -\\   7   7   ]
^.___~==-._    ~-{  .-~ .  \\ Y . /    |        GARUDA
 <__ ~--.  ~       /_/   \   \I  Y   : |      INDONESIA
   ^-.__           ~(_/   \   >._:   | l _____
       ^--.,___.-~-  /_/   !  \-.~---l_ /     ---.
              (_/ .  ~(   /      -~---,Y   '$white'-=b-'$red'. _)
               (_/ .  \  :           / l      c-~o \
                \ /    \.    .     .^   \_.-~~~--.  )
                 (_/ .   \  /     /       !       )/
                  / / _.   /.   ./:      /        v
                  ~(_/ .   /    _  \  .-<_
                    /_/ . / .-~- \.  / \  \          ,z=.
                    ~( /   /  :   | K   <-.~-.______//
                      \-,.    l   I/ \_    __{--->._(==.
                       //(     \  <    ~~~-     //
                      // /\     \  \     ,v=.  ((
                    .^. / /\     \  }__ //===- 
                   / / / /  /-.,__ {---(==-
                 .^ /       :  T  ~|   ll      
                / .  .  . : | :!        \\
               (_/  /   | | j-/          ~^
                 ~-<_(_.^-~/'
      exit
fi

echo
echo -e -n "Back to Menu? (y/n) :";
read again;

    while  [ $again != 'y' ] && [ $again != 'Y' ] && [ $again != 'n' ] && [ $again != 'N' ];
    do
       echo -n "Back to menu (y/n) :";
       read again;
    done
done
#DISCLAIMER: modifications, changes, or alterations to this sourcecode is acceptable, however,
#any public releases utilizing this code must be approved by writen this tool 